[package]
name = "film-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
rawloader = "0.37.1"
libraw = "0.1.1"
clap = { version = "4.5.53", features = ["derive"] }
[build-dependencies]
pkg-config = "0.3.32"
bindgen = "0.72.1"
